//Base Docker url: http://localhost/api
//Base local url: http://localhost:5000
@base_url = http://localhost/api

### Endpoint de login
POST {{base_url}}/login
Content-Type: application/json

{
    "email": "v@v.com",
    "password": "1!Aa"
}