//Base Docker url: http://localhost/api
//Base local url: http://localhost:5000
@base_url = http://localhost/api

### Criação de usuários
POST {{base_url}}/user
Content-Type: application/json

{
    "email": "i@i.com",
    "password": "1!Aa",
    "name": "Ivan Pinheiro"
}

### Retorna e-mail e nome do JWT
GET {{base_url}}/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaUBpLmNvbSIsIm5hbWUiOiJJdmFuIEJhcmIiLCJpYXQiOjE3MTk3Njg5MzYsImV4cCI6MTcyMjM2MDkzNn0.USF3ZhuMMdcG5n3yjwSZ8p0Ee_YaHacTT5Et6H_LIcc

### Atualiza o nome
POST {{base_url}}/user/update-name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaUBpLmNvbSIsIm5hbWUiOiJJdmFuIFBpbmhlaXJvIiwiaWF0IjoxNzE5NzE0NTg2LCJleHAiOjE3MjIzMDY1ODZ9.nFyfgD9Pa5GBA-QCGAW96AkvYtIE887-420jpq7626U

{
    "name": "Ivan B P"
}

### Atualiza a senha
POST {{base_url}}/user/update-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaUBpLmNvbSIsIm5hbWUiOiJJdmFuIFBpbmhlaXJvIiwiaWF0IjoxNzE5NzE0NTg2LCJleHAiOjE3MjIzMDY1ODZ9.nFyfgD9Pa5GBA-QCGAW96AkvYtIE887-420jpq7626U

{
    "password": "1!Aa!123"
}

### Retorna e-mail e nome do banco de dados
GET {{base_url}}/user/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaUBpLmNvbSIsIm5hbWUiOiJJdmFuIEJhcmIiLCJpYXQiOjE3MTk3Njg5MzYsImV4cCI6MTcyMjM2MDkzNn0.USF3ZhuMMdcG5n3yjwSZ8p0Ee_YaHacTT5Et6H_LIcc