
//Base Docker url: http://localhost/api
//Base local url: http://localhost:5000
@base_url = http://localhost/api

###
GET {{base_url}}/activities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoidkB2LmNvbSIsIm5hbWUiOiJJdmFuIFBpbmhlaXJvIiwiaWF0IjoxNzE5Nzc4MTM2LCJleHAiOjE3MjIzNzAxMzZ9.3NC2FxF8bfR6oXpRQjex2QaaPasNWha9qvUEuUmaYeo

###
GET {{base_url}}/activities/6681b6c9763b10ccd0fa72d1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoidkB2LmNvbSIsIm5hbWUiOiJJdmFuIFBpbmhlaXJvIiwiaWF0IjoxNzE5Nzc4MTM2LCJleHAiOjE3MjIzNzAxMzZ9.3NC2FxF8bfR6oXpRQjex2QaaPasNWha9qvUEuUmaYeo

###
POST  {{base_url}}/activities
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoidkB2LmNvbSIsIm5hbWUiOiJJdmFuIFBpbmhlaXJvIiwiaWF0IjoxNzE5Nzc4MTM2LCJleHAiOjE3MjIzNzAxMzZ9.3NC2FxF8bfR6oXpRQjex2QaaPasNWha9qvUEuUmaYeo

{
    "title": "Cálculo",
    "author": "Vilmar",
    "authorEmail": "v@v.com",
    "activitiesWeek": [{
    	"dayWeek": "1",
    	"activityTime": [{
    		"start": "10:30",
    		"end": "12:30",			
			"presenceActivity":[{"dateTime":"2024-05-10T20:30", "isPresent": true}]
    	}, {
    		"start": "19:30",
    		"end": "20:30",
			"presenceActivity":[{"dateTime":"2024-05-10T20:30", "isPresent": false}]
    	}]
    }, {
    	"dayWeek": "2",
    	"activityTime": [{
    		"start": "09:00",
    		"end": "10:30",
			"presenceActivity":[{"dateTime":"2024-05-10T20:30", "isPresent": false}]
    	}, {
    		"start": "13:30",
    		"end": "17:30",
			"presenceActivity":[{"dateTime":"2024-05-10T20:30", "isPresent": true}]
    	}]
    }],
    "startDate": "2024-05-10",
    "endDate": "2024-05-10",
    "createdAt": "2024-05-10",
    "updatedAt": "2024-05-05",
    "category": "USP"
}

###
PATCH   {{base_url}}/activities/6682d4f229149090cadfc6bc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoidkB2LmNvbSIsIm5hbWUiOiJJdmFuIFBpbmhlaXJvIiwiaWF0IjoxNzE5Nzc4MTM2LCJleHAiOjE3MjIzNzAxMzZ9.3NC2FxF8bfR6oXpRQjex2QaaPasNWha9qvUEuUmaYeo

{
    "title": "POO",
    "author": "Vilmar",
    "authorEmail": "v@v.com",
    "activitiesWeek": [{
    	"dayWeek": "1",
    	"activityTime": [{
    		"start": "10:30",
    		"end": "12:30"
    	}, {
    		"start": "19:30",
    		"end": "20:30"
    	}]
    }, {
    	"dayWeek": "2",
    	"activityTime": [{
    		"start": "09:00",
    		"end": "10:30"
    	}, {
    		"start": "13:30",
    		"end": "17:30"
    	}]
    }],
    "startDate": "2024-05-10",
    "endDate": "2024-05-10",
	"presenceActivity":[{"dateTime":"2024-05-10T20:30", "isPresent": true}],
    "createdAt": "2024-05-10",
    "updatedAt": "2024-05-05",
    "category": "USP"
}

###
DELETE    {{base_url}}/activities/6683081d991ef9286fe4ffe5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoidkB2LmNvbSIsIm5hbWUiOiJJdmFuIFBpbmhlaXJvIiwiaWF0IjoxNzE5Nzc4MTM2LCJleHAiOjE3MjIzNzAxMzZ9.3NC2FxF8bfR6oXpRQjex2QaaPasNWha9qvUEuUmaYeo