
//Base Docker url: http://localhost/api
//Base local url: http://localhost:5000
@base_url = http://localhost/api

###
GET {{base_url}}/activities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaUBpLmNvbSIsIm5hbWUiOiJJdmFuIEJhcmIiLCJpYXQiOjE3MTk3Njg5MzYsImV4cCI6MTcyMjM2MDkzNn0.USF3ZhuMMdcG5n3yjwSZ8p0Ee_YaHacTT5Et6H_LIcc

###
GET {{base_url}}/activities/6681b6c9763b10ccd0fa72d1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaUBpLmNvbSIsIm5hbWUiOiJJdmFuIEJhcmIiLCJpYXQiOjE3MTk3Njg5MzYsImV4cCI6MTcyMjM2MDkzNn0.USF3ZhuMMdcG5n3yjwSZ8p0Ee_YaHacTT5Et6H_LIcc

###
POST  {{base_url}}/activities
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaUBpLmNvbSIsIm5hbWUiOiJJdmFuIEJhcmIiLCJpYXQiOjE3MTk3Njg5MzYsImV4cCI6MTcyMjM2MDkzNn0.USF3ZhuMMdcG5n3yjwSZ8p0Ee_YaHacTT5Et6H_LIcc

{
    "title": "POO",
    "author": "Ivan",
    "authorEmail": "i@i.com",
        "activitiesWeek": [{
    	"dayWeek": "1",
    	"activityTime": [{
    		"start": "10:30",
    		"end": "12:30"
    	}, {
    		"start": "19:30",
    		"end": "20:30"
    	}]
    }, {
    	"dayWeek": "2",
    	"activityTime": [{
    		"start": "09:00",
    		"end": "10:30"
    	}, {
    		"start": "13:30",
    		"end": "17:30"
    	}]
    }],
    "startDate": "2024-05-10",
    "endDate": "2024-05-10",
    "createdAt": "2024-05-10",
    "updatedAt": "2024-05-05",
    "category": "USP"
}

###
PATCH   {{base_url}}/activities/6681b6c9763b10ccd0fa72d1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaUBpLmNvbSIsIm5hbWUiOiJJdmFuIEJhcmIiLCJpYXQiOjE3MTk3Njg5MzYsImV4cCI6MTcyMjM2MDkzNn0.USF3ZhuMMdcG5n3yjwSZ8p0Ee_YaHacTT5Et6H_LIcc

{
    "title": "POO",
    "author": "Ivan",
    "authorEmail": "i@i.com",
        "activitiesWeek": [{
    	"dayWeek": "1",
    	"activityTime": [{
    		"start": "10:30",
    		"end": "12:30"
    	}, {
    		"start": "15:30",
    		"end": "20:30"
    	}]
    }, {
    	"dayWeek": "2",
    	"activityTime": [{
    		"start": "09:00",
    		"end": "10:30"
    	}, {
    		"start": "13:30",
    		"end": "17:30"
    	}]
    }],
    "startDate": "2024-05-10",
    "endDate": "2024-05-10",
    "createdAt": "2024-05-10",
    "updatedAt": "2024-05-05",
    "category": "USP"
}

###
DELETE    {{base_url}}/activities/6681b125e8a97839a6783f50
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaUBpLmNvbSIsIm5hbWUiOiJJdmFuIEJhcmIiLCJpYXQiOjE3MTk3Njg5MzYsImV4cCI6MTcyMjM2MDkzNn0.USF3ZhuMMdcG5n3yjwSZ8p0Ee_YaHacTT5Et6H_LIcc